config/routes.rb
# frozen_string_literal: true

require 'api_constraints'

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  scope module: :v1, constraints: ApiConstraints.new(version: 1, default: false) do
    resources :folders, path: 'folders', only: %i[index new create edit update show destroy],
                        path_names: { new: 'new', edit: 'edit' }, param: :folder_id do
      member do
        resources :documents, path: 'documents', only: %i[index new create edit update show destroy],
                              path_names: { new: 'new', edit: 'edit' }, param: :document_id
      end
    end
  end
end

app/models/concerns/document/associations.rb
# frozen_string_literal: true

class Document < ApplicationRecord
  module Associations
    extend ActiveSupport::Concern
    included do
      belongs_to :folder
    end
  end
end

app/models/concerns/document/validations.rb
# frozen_string_literal: true

class Document < ApplicationRecord
  module Validations
    extend ActiveSupport::Concern
    included do
      validates :name, presence: true, uniqueness: true
      validates :file, presence: true
    end
  end
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :directory
  has_one_attached :attached_content
  validates :name, presence: true
  validates :content, presence: true, if: :database?

  enum storage_type: { database: 'database', disk: 'disk', s3: 's3' }

  before_save :update_attached_content_key, unless: :database?

  def assign_content(file_path)
    if database?
      self.content = File.read file_path
    else
      io = File.open file_path
      filename = file_path.match(%r{/([^/]+)$})[1]
      attached_content.attach(io:, filename:)
    end
  end

  private

  def update_attached_content_key
    attached_content.service_name = storage_type.to_sym

    return unless attached_content.attached?

    key = "#{directory.full_path}/#{name}.#{SecureRandom.uuid}"
    attached_content.blob.update key:
  end
end

app/models/documents/aws_document.rb
module Documents
  class AWSDocument < Document
    has_one_attached :file, service: :amazon
  end
end

app/models/documents/local_document.rb
module Documents
  class LocalDocument < Document
    has_one_attached :file, service: :local
  end
end

app/controllers/api/v1/documents_controller.rb
module Api
  module V1
    class DocumentsController < ApplicationController
      def create
        render json: Documents::CreateService.call(document_params)
      end
      
      def update
        render json: Documents::UpdateService.call(document_params)
      end

      def destroy
        render json: Documents::DestroyService.call(document_params)
      end

      private

      def document_params
        @document_params ||= params.permit(:name, :directory_id, :file, :provider)
      end
    end
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :update, :destroy]

  before_action do
    ActiveStorage::Current.host = request.base_url
  end

  def index
    @documents = Document.all.where(folder_id:)

    render json: @documents.paginate(page:)
  end

  def show
    render json: @document
  end

  def create
    @document = Document.create!(document_params)
    render json: @document, status: :created
  end

  def update
    @document.update!(document_params)

    render json: @document
  end

  def destroy
    @document.destroy
  end

  private

  def folder_id
    params[:folder_id]
  end

  def page
    params[:page]
  end

  def set_document
    @document = Document.find(params[:id])
  end

  def document_params
    params.require(:document).permit(:name, :content, :folder_id, :file)
  end
end

app/controllers/v1/documents_controller.rb
# frozen_string_literal: true

module V1
  class DocumentsController < ApplicationController
    before_action :set_document, only: %i[update show destroy]

    def index
      render json: DocumentsService::ListDocumentsService.new(paginate_params).call
    end

    def create
      document = DocumentsService::CreateDocumentService.new(params[:folder_id], document_params).call
      return render json: { errors: document.errors }, status: :unprocessable_entity if document.errors.any?

      render json: document, status: :created
    end

    def update
      document = DocumentsService::UpdateDocumentService.new(@document, document_params).call
      return render json: { errors: document.errors }, status: :unprocessable_entity if document.errors.any?

      render json: { document:, message: 'Document updated successfully' }, status: :ok
    end

    def show
      return render json: @document, status: :ok if @document.present?

      render json: { errors: ['Document not found'] }, status: :not_found
    end

    def destroy
      unless DocumentsService::DeleteDocumentService.new(@document.id).call
        return render json: { errors: [e.message] }, status: :unprocessable_entity
      end

      render json: { message: 'Document deleted successfully' }, status: :ok
    end

    private

    def document_params
      params.require(:document).permit(:name, :file)
    end

    def set_document
      if params[:document_id].blank?
        return render json: { errors: ['Document_id is required'] }, status: :unprocessable_entity
      end

      @document = DocumentsService::GetDocumentService.new(params[:document_id]).call
    end
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_document.html.erb
<div id="<%= dom_id document %>">
  <p>
    <strong>Name:</strong>
    <%= document.name %>
  </p>

  <p>
    <strong>Path:</strong>
    <%= document.path %>
  </p>

</div>

app/views/documents/_form.html.erb
<%= form_with(model: document) do |form| %>
  <% if document.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
        <% document.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :path, style: "display: block" %>
    <%= form.text_field :path %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render "form", document: @document %>

<br>

<div>
  <%= link_to "Show this document", @document %> |
  <%= link_to "Back to documents", documents_path %>
</div>

app/views/documents/index.html.erb
<div class="container">
<% if !flash[:notice].blank? %>
   <div>
      <%= flash[:notice] %>
   </div>
<% end %>

<h1>Documents</h1>

<%= link_to "New Document", new_document_path %>

<div id="documents">
  <% @documents.each do |document| %>
    <%= render document %>
    <p>
      <%= link_to "Show this document", document %>
    </p>
  <% end %>
</div>

app/views/documents/new.html.erb
<div class="container">
<% if !@document.errors.empty? %>
   <div>

      <ul>
         <% @document.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>

   </div>
<% end %>

<div>
   <%= form_for @document, html: { multipart: true } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <br><br>
      <%= f.label :path %>
      <%= f.file_field :path %>
      <%= f.label :folder_id, 'Parent', style: "display: block" %>
      <%= collection_select(:document, :folders_id, Folder.nameAsc, :id, :name, include_blank: true) %>
      <br>
      <%= f.submit "Save" %>
   <% end %>
</div>
</div>

app/views/documents/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @document %>

<div>
  <%= link_to "Edit this document", edit_document_path(@document) %> |
  <%= link_to "Back to documents", documents_path %>

  <%= button_to "Destroy this document", @document, method: :delete %>
</div>